pipeline{
    agent any
    stages{
        stage("Github"){
            steps{
                git branch: 'main', credentials: 'jenkins', url : 'https://github.com/sobitsingh/e-commerce-k8.git'
            }
        }
    }
}
