pipeline{
    agent any
    tools{
        go 'go_jenkins'
    }
    environment{
        PRODUCT_CATALOG_PORT=8081
        SONAR_PROJECT_KEY = "product-cat"
        SONAR_HOST_URL = "http://18.213.4.185:9000"
        SONAR_SCANNER_HOME = tool "sonar"
        ECR_REGISTRY = ""
        ECR_REPO = ""
    }
    stages{
        stage("Github"){
            steps{
                git branch: 'main', credentialsId: 'jenkins', url : 'https://github.com/sobitsingh/e-commerce-k8.git'
            }
        }
        stage('Build'){
            steps{
                sh """
                    cd ultimate-devops-project-demo/src/product-catalog
                    go build -o product-catalog . 
                """
            }
        }
        stage('Static_code_analysis'){
            steps{
                withCredentials([string(credentialsId: 'sonar_token', variable: 'SONAR_TOKEN')]) {
                    withSonarQubeEnv('sonar'){
                        sh """
                            ${SONAR_SCANNER_HOME}/bin/sonar-scanner \
                            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                            -Dsonar.sources=. \
                            -Dsonar.host.url=${SONAR_HOST_URL} \
                            -Dsonar.login=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }
        stage("Docker"){
            steps{
                script{
                    docker.build("prod-catalog-${ECR_REGISTRY}/${ECR_REPO}:${BUILD_ID}")
                }
            }
        }
        stage('Trivy Scan'){
            steps{
                sh "trivy --severiry CRITICAL,HIGH --no-progress --format trivy_results.txt --image product-catalog: ${BUILD.ID}"
            }
        }
        stage('ECR login'){
            steps{
                sh "aws ecr get-login-password --region us-west-1"
            }
        }
        stage('ECR Push'){
            steps{
                script{
                    docker.image("prod-catalog-${ECR_REGISTRY}/${ECR_REPO}:${BUILD_ID}").push()
                }
            }
        }
    }
}
