---
- name: Install and configure Nginx with custom index
  hosts: all
  remote_user: root
  become: true

  vars:
    nginx_root: /var/www/html

  tasks:
    - name: Ensure nginx is installed (Debian)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure nginx is installed (RedHat)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Deploy custom index.html
      copy:
        src: files/index.html
        dest: "{{ nginx_root }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Restart nginx

    - name: Ensure nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
