name: product-catalog
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Build
        run: |
          cd ./ultimate-devops-project-demo/src/product-catalog
          go mod download
          go build -o product-catalog-service main.go
      - name: Unit Test
        run: |
          cd ./ultimate-devops-project-demo/src/product-catalog
          go test -v ./...
  code-quality:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint # check for unused variables and outdated packages dependency
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          export PATH=$(go env GOPATH)/bin:$PATH
          echo "Running golangci-lint...$PATH"
          golangci-lint run ./ultimate-devops-project-demo/src/product-catalog/... --timeout 5m
  docker-build:
      runs-on: ubuntu-latest
      needs: [build, code-quality]
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ultimate-devops-project-demo/src/product-catalog
          file: ./ultimate-devops-project-demo/src/product-catalog/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_id-  }}
  update-k8-manifests:
      runs-on: ubuntu-latest
      needs: [docker-build]
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Update k8s manifests
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_id }}|g" ./ultimate-devops-project-demo/kubernetes/productcatalog/deploy.yaml
      - name: commit and push changes
        run: |
          git config --global user.name "sobitsingh007"
          git config --global user.email "sobitsingh007@gmail.com"
          git add ./ultimate-devops-project-demo/kubernetes/productcatalog/deploy.yaml
          git commit -m "update image to [CI] ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_id }}"
          git push

          